# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-7edbeaab-f6d6-4e4e-9234-eb517eb5a2c3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-7edbeaab-f6d6-4e4e-9234-eb517eb5a2c3".device = "/dev/disk/by-uuid/7edbeaab-f6d6-4e4e-9234-eb517eb5a2c3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B4E1-18E3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
